### ISSUE TITLE
demo起不来啊

### ISSUE THREAD

**Issue by EthanOrange** [larry011/react-isomorph-demo#1]

**Comment by EthanOrange** [comment]
依赖install之后
运行package里面的 start 和 dev-server-koa

报错如下：
`TypeError: Cannot read property 'pending' of undefined
pending
webpack:///src/module/Home/Index.jsx:47:36
Index.render
webpack:///~/react-proxy/modules/createPrototypeProxy.js:44
http://127.0.0.1:23456/js/index.bundle.js?727718259f9d8c101da0:32137:21
measureLifeCyclePerf
webpack:///~/react-dom/lib/ReactCompositeComponent.js:75
ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
webpack:///~/react-dom/lib/ReactCompositeComponent.js:794
ReactCompositeComponentWrapper._renderValidatedComponent
webpack:///~/react-dom/lib/ReactCompositeComponent.js:821
ReactCompositeComponentWrapper.performInitialMount
webpack:///~/react-dom/lib/ReactCompositeComponent.js:361
ReactCompositeComponentWrapper.mountComponent
webpack:///~/react-dom/lib/ReactCompositeComponent.js:257
Object.mountComponent
webpack:///~/react-dom/lib/ReactReconciler.js:45
ReactCompositeComponentWrapper.performInitialMount
webpack:///~/react-dom/lib/ReactCompositeComponent.js:370
ReactCompositeComponentWrapper.mountComponent
webpack:///~/react-dom/lib/ReactCompositeComponent.js:257
Object.mountComponent
webpack:///~/react-dom/lib/ReactReconciler.js:45
ReactCompositeComponentWrapper.performInitialMount
webpack:///~/react-dom/lib/ReactCompositeComponent.js:370
ReactCompositeComponentWrapper.performInitialMountWithErrorHandling
webpack:///~/react-dom/lib/ReactCompositeComponent.js:316
ReactCompositeComponentWrapper.mountComponent
webpack:///~/react-dom/lib/ReactCompositeComponent.js:255
Object.mountComponent
webpack:///~/react-dom/lib/ReactReconciler.js:45`

**Comment by larry011** [comment]
@EthanOrange 非常感谢你指出问题，报错是因为两个命令不能同时使用的，`dev-server-koa`是用来开发模式，`start`是在生成服务器开启的。
不好意思哇，博客的文章没有和项目代码同步更新，我近期会整理一下。

开发模式只需要执行`dev-server-koa`即可。
生成模式要先运行`dist`和`dist-ssr-bundle`，输出资源文件，再运行`start`
上面我今天早上（6-29）都测试了一般，没发现问题。如果还有不懂的地方可以在[segmentfault](https://segmentfault.com/u/larry_)上私聊我

**Comment by EthanOrange** [comment]
@larry011 感谢回馈
你可以试下 clone 这个包  然后npm i   然后run dev-server-koa 是否能正常dev
我刚又clone了一次 还是报错...

**Comment by larry011** [comment]
@EthanOrange 我删了node_modules，重新cnpm i 了，还是没发现问题。你pull一下，看下是不是最新的版本，在master分支。
我的系统版本是win10 x64，node v7.7.1，npm 4.1.2。你的编译环境是怎么样的？

`TypeError: Cannot read property 'pending' of undefined pending `
上面这句代码是没有找到pending属性，你看下你的redux库是不是没安装好。
![image](https://user-images.githubusercontent.com/10259971/27716690-ab0a0d16-5d72-11e7-8430-c846f2fce5a0.png)
